version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - log-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - log-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    container_name: filebeat
    user: "0:0"
    volumes:
      - /var/log/myapp.log:/var/log/myapp.log:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - log-network
    depends_on:
      - elasticsearch

networks:
  log-network:
    driver: bridge

volumes:
  log-volume:
    external: true