version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/db_user) -d $$(cat /run/secrets/db_name)"]
      interval: 5s
      timeout: 3s
      retries: 5
    secrets:
      - db_user
      - db_password
      - db_name
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    ports:
      - "50051:50051"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
  migrate:
    build: 
      context: .
      dockerfile: migrations.Dockerfile
    volumes:
      - ./db/migrations:/db/migrations
    entrypoint: /entrypoint.sh
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db_user
      - db_password
      - db_name

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt

volumes:
  pg_data:
