// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/application": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Создать заявку",
                "parameters": [
                    {
                        "description": "Данные заявки",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Andronzi_credit-origination_internal_transport_dto_request.CreditApplicationCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Andronzi_credit-origination_internal_transport_dto_response.CreditApplicationResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Andronzi_credit-origination_internal_transport_dto_request.CreditApplicationCreateRequest": {
            "type": "object",
            "required": [
                "amount",
                "term"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 150000.5
                },
                "term": {
                    "type": "integer",
                    "example": 12
                }
            }
        },
        "github_com_Andronzi_credit-origination_internal_transport_dto_response.CreditApplicationResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 150000.5
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-10-01T12:34:56Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "NEW"
                },
                "term": {
                    "type": "integer",
                    "example": 12
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-01T12:34:56Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Credit Origination API",
	Description:      "API для управления кредитными заявками",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
