basePath: /
definitions:
  github_com_Andronzi_credit-origination_internal_transport_dto_request.CreditApplicationCreateRequest:
    properties:
      amount:
        example: 150000.5
        type: number
      term:
        example: 12
        type: integer
    required:
    - amount
    - term
    type: object
  github_com_Andronzi_credit-origination_internal_transport_dto_response.CreditApplicationResponse:
    properties:
      amount:
        example: 150000.5
        type: number
      created_at:
        example: "2023-10-01T12:34:56Z"
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      status:
        example: NEW
        type: string
      term:
        example: 12
        type: integer
      updated_at:
        example: "2023-10-01T12:34:56Z"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления кредитными заявками
  title: Credit Origination API
  version: "1.0"
paths:
  /application:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные заявки
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_Andronzi_credit-origination_internal_transport_dto_request.CreditApplicationCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Andronzi_credit-origination_internal_transport_dto_response.CreditApplicationResponse'
      summary: Создать заявку
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
